import { createServer } from 'node:http';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { resolve, join, extname } from 'node:path';
import { randomBytes, createHash } from 'node:crypto';
const root=process.cwd(), dataDir=process.env.DATA_DIR||join(root,'data'), file=join(dataDir,'dic404.json'), types={'.html':'text/html','.js':'text/javascript','.css':'text/css'};
await mkdir(dataDir,{recursive:true});let db=existsSync(file)?JSON.parse(await readFile(file,'utf8')):{users:[],sessions:[],cases:[],messages:[],maps:[]};const save=()=>writeFile(file,JSON.stringify(db,null,2));
const id=p=>p+'_'+randomBytes(10).toString('hex'), cookie=r=>Object.fromEntries((r.headers.cookie||'').split(';').filter(Boolean).map(x=>x.trim().split('='))), me=r=>{let s=db.sessions.find(x=>x.id===cookie(r).dic_session);return s&&db.users.find(x=>x.id===s.userId)}, safe=u=>{let{admin,...x}=u;return x}, out=(r,s,x,h={})=>{r.writeHead(s,{'Content-Type':'application/json',...h});r.end(JSON.stringify(x))}, json=async r=>{let x='';for await(const c of r)x+=c;return x?JSON.parse(x):{}};
async function api(req,res,p){let u=me(req),b;
 if(p==='/auth/google'&&req.method==='POST'){b=await json(req);let g;try{g=await (await fetch('https://oauth2.googleapis.com/tokeninfo?id_token='+encodeURIComponent(b.credential||''))).json()}catch{return out(res,502,{error:'Não foi possível validar o Google.'})}if(g.aud!=='623410122056-cb5sgofln7pfjjc30um7svu3dpf88ud2.apps.googleusercontent.com'||!g.email_verified)return out(res,401,{error:'Token Google inválido.'});u=db.users.find(x=>x.email===g.email)||{id:id('agent'),email:g.email,name:g.name||g.email,role:'Agente',bio:'',createdAt:Date.now()};if(!db.users.includes(u))db.users.push(u);let s={id:id('session'),userId:u.id};db.sessions.push(s);await save();return out(res,200,{user:safe(u)},{'Set-Cookie':`dic_session=${s.id}; HttpOnly; SameSite=Lax; Path=/`})}
 if(!u)return out(res,401,{error:'Faça login.'});
 if(p==='/me')return out(res,200,{user:safe(u)});
 if(p==='/auth/admin'&&req.method==='POST'){b=await json(req);if(createHash('sha256').update(b.password||'').digest('hex')!=='835e5206a3c317744bfa542894ef7920f20fdc74e8783432912a0adc28862f24')return out(res,401,{error:'Senha inválida.'});u.admin=true;await save();return out(res,200,{user:safe(u)})}
 if(p==='/cases'){if(req.method==='GET')return out(res,200,{cases:db.cases.filter(c=>c.ownerId===u.id||u.admin||u.role==='Impostor')});if(req.method==='POST'){b=await json(req);let c={id:id('case'),ownerId:u.id,name:b.name,number:b.number||'404-'+(db.cases.length+1),state:b.state||'andamento',story:b.story||'',notes:b.notes||'',date:Date.now()};db.cases.push(c);await save();return out(res,201,{case:c})}}
 if(p==='/messages'){if(req.method==='GET')return out(res,200,{messages:db.messages.filter(m=>m.members.includes(u.id))});if(req.method==='POST'){b=await json(req);if(!b.members?.includes(u.id)||!b.text)return out(res,400,{error:'Mensagem inválida.'});let m={id:id('msg'),members:b.members,senderId:u.id,text:b.text,createdAt:Date.now(),deleted:false};db.messages.push(m);await save();return out(res,201,{message:m})}}
 if(p==='/maps'){if(req.method==='GET')return out(res,200,{maps:db.maps.filter(m=>m.ownerId===u.id||u.admin||u.role==='Impostor')});if(req.method==='POST'){b=await json(req);let m=db.maps.find(x=>x.id===b.id);if(m&&m.ownerId!==u.id&&!u.admin)return out(res,403,{error:'Sem acesso.'});if(m)Object.assign(m,b);else{m={id:id('map'),ownerId:u.id,...b};db.maps.push(m)}await save();return out(res,200,{map:m})}}
 return out(res,404,{error:'Rota não encontrada.'})}
createServer(async(req,res)=>{try{let url=new URL(req.url,'http://localhost');if(url.pathname.startsWith('/api/'))return api(req,res,url.pathname.slice(4));let f=resolve(root,url.pathname==='/'?'index.html':url.pathname.slice(1));if(!f.startsWith(root))return out(res,403,{error:'Bloqueado'});let d=await readFile(f);res.writeHead(200,{'Content-Type':types[extname(f)]||'application/octet-stream'});res.end(d)}catch(e){out(res,e.code==='ENOENT'?404:500,{error:'Erro do servidor'})}}).listen(process.env.PORT||4173,'0.0.0.0',()=>console.log('D.I.C. Caso 404 iniciado'));
